Fix `self` scope
grafana/jsonnet-language-server pull request #23
Opened 2022-01-14 02:26 UTC by julienduchesne

Fields outside of the scope of `self` are currently being resolved
See the test for an example
Fixes https://github.com/grafana/jsonnet-language-server/issues/2

2022-01-14 16:38 UTC, zzehring commented on pkg/position/range.go
> +// RangeGreaterThan returns true if the first range is greater than the second.
```suggestion
// RangeGreaterOrEqual returns true if the first range is greater than the second.
```
Also, I wonder if we should define/expand what `greater` means. Probably safe to have as is tho.

2022-01-14 19:08 UTC, zzehring requested changes
Very nice fix on this!

2022-01-25 02:03 UTC, julienduchesne commented on pkg/processing/object.go
> +	}
It's not equivalent it seems. My tests are failing with the new code 😕

2022-01-25 03:10 UTC, julienduchesne commented
@zzehring Addressed your comments!

2022-01-26 19:38 UTC, zzehring approved these changes
LGTM!

2022-01-27 11:32 UTC, merged